### ISSUE TITLE
No git tags

### ISSUE THREAD

**Issue by frewsxcv** [bradleyayers/django-celery-transactions#15]
I'd like to find out what changed between releases, yet there's no git tags, nor a changelog

**Comment by nicolasgrasset** [comment]
Hey, I took over the project and pypi releases (https://github.com/fellowshipofone/django-celery-transactions).

I just updated the tags and added a changelog

**Comment by frewsxcv** [comment]
Awesome, great work @fellowshipofone :sparkles: :sparkles:
